name: Install Terragrunt

description: Installs Terragrunt

inputs:
  version:
    description: The version to Install
    required: true
    default: '0.53.4'

runs:
  using: composite
  steps:
    - name: Download
      shell: bash
      run: "curl https://github.com/gruntwork-io/terragrunt/releases/download/v${inputs.version}/terragrunt_linux_amd64 -o terragrunt"
    - name: Set permissions
      shell: bash
      run: chmod u+x terragrunt
    - name: Move file
      shell: bash
      run: mv terragrunt $HOME/.local/bin/terragrunt
    - name: Add to path
      shell: bash
      run: echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      