name: Apply

concurrency:
    cancel-in-progress: false
    group: '${{ github.workflow }}'

on:
  workflow_dispatch: 

permissions:
    contents: read

jobs:
    st_0_state:
        name: "0: state"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: "Check: ELEPHANTSQL_APIKEY"
              uses: ./.github/actions/check-env-var
              with:
                env_var: ${{ secrets.ELEPHANTSQL_APIKEY }}
            - name: "Check: PG_CONN_STR"
              uses: ./.github/actions/check-env-var
              with:
                env_var: ${{ secrets.PG_CONN_STR }}
    st_1_github:
      name: "1: github"
      needs: [st_0_state]
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3
          - uses: opentofu/setup-opentofu@v1
          - name: "Check: GH_ORG_ADMIN"
            uses: ./.github/actions/check-env-var
            with:
              env_var: ${{ secrets.GH_ORG_ADMIN }}
          - name: "Check: GANDI_KEY"
            uses: ./.github/actions/check-env-var
            with:
              env_var: ${{ secrets.GANDI_KEY }}
          - name: Apply
            env:
              PG_CONN_STR: ${{ secrets.PG_CONN_STR }}
              GITHUB_TOKEN: ${{ secrets.GH_ORG_ADMIN }}

              TF_VAR_elephantsql_api_key: ${{ secrets.ELEPHANTSQL_APIKEY }}
              TF_VAR_pg_conn_str: ${{ secrets.PG_CONN_STR }}
              TF_VAR_gh_org_admin: ${{ secrets.GH_ORG_ADMIN }}
              TF_VAR_gandi_key: ${{ secrets.GANDI_KEY }}
              TF_VAR_improvmx_api_token:  ${{ secrets.IMPROVMX_API_TOKEN }}
            working-directory: stages/1-github
            run: |-
              tofu init
              tofu apply -auto-approve -lock-timeout=3s -input=false
    st_2_domain:
      name: "2: domain"
      needs: [st_1_github]
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3
          - uses: opentofu/setup-opentofu@v1
          - name: Apply
            env:
              PG_CONN_STR: ${{ secrets.PG_CONN_STR }}
              GANDI_KEY:  ${{ secrets.GANDI_KEY }}
            working-directory: stages/2-domain
            run: |-
              tofu init
              tofu apply -auto-approve -lock-timeout=3s -input=false
    st_3_email:
      name: "3: email"
      needs: [st_2_domain]
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3
          - uses: opentofu/setup-opentofu@v1
          - name: Apply
            env:
              PG_CONN_STR: ${{ secrets.PG_CONN_STR }}
              IMPROVMX_API_TOKEN:  ${{ secrets.IMPROVMX_API_TOKEN }}
            working-directory: stages/3-email
            run: |-
              tofu init
              tofu apply -auto-approve -lock-timeout=3s -input=false

                